import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Sidebar from "@/components/Sidebar";

import { getCookie } from "@/hooks/useCookie";
import SessionProvider from "@/context/SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <div className="relative flex">
            <div
              className="h-screen shadow overflow-y-auto overflow-x-hidden print:hidden">
              <Sidebar />
            </div>
            <main className="flex-1 h-screen overflow-y-auto bg-slate-50">
              {children}
            </main>
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
